/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        "dataPath": string;
        "url": string;
    }
    interface RicardoColumn {
        "label": string;
        "name": string;
    }
    interface RicardoStatistics {
        "url": string;
    }
    interface RicardoTable {
        "dataPath": string;
        "url": string;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLRicardoColumnElement extends Components.RicardoColumn, HTMLStencilElement {
    }
    var HTMLRicardoColumnElement: {
        prototype: HTMLRicardoColumnElement;
        new (): HTMLRicardoColumnElement;
    };
    interface HTMLRicardoStatisticsElement extends Components.RicardoStatistics, HTMLStencilElement {
    }
    var HTMLRicardoStatisticsElement: {
        prototype: HTMLRicardoStatisticsElement;
        new (): HTMLRicardoStatisticsElement;
    };
    interface HTMLRicardoTableElement extends Components.RicardoTable, HTMLStencilElement {
    }
    var HTMLRicardoTableElement: {
        prototype: HTMLRicardoTableElement;
        new (): HTMLRicardoTableElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "ricardo-column": HTMLRicardoColumnElement;
        "ricardo-statistics": HTMLRicardoStatisticsElement;
        "ricardo-table": HTMLRicardoTableElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        "dataPath"?: string;
        "url"?: string;
    }
    interface RicardoColumn {
        "label"?: string;
        "name"?: string;
    }
    interface RicardoStatistics {
        "url"?: string;
    }
    interface RicardoTable {
        "dataPath"?: string;
        "url"?: string;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "ricardo-column": RicardoColumn;
        "ricardo-statistics": RicardoStatistics;
        "ricardo-table": RicardoTable;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "ricardo-column": LocalJSX.RicardoColumn & JSXBase.HTMLAttributes<HTMLRicardoColumnElement>;
            "ricardo-statistics": LocalJSX.RicardoStatistics & JSXBase.HTMLAttributes<HTMLRicardoStatisticsElement>;
            "ricardo-table": LocalJSX.RicardoTable & JSXBase.HTMLAttributes<HTMLRicardoTableElement>;
        }
    }
}
